---
version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: 06:00
    # Group related updates into a single PR
    groups:
      actions-minor-patch:
        patterns:
          - '*'  # all actions
        update-types: [minor, patch]
    open-pull-requests-limit: 5
    labels: [dependencies, github-actions]
