---
global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [prometheus:9090]

  - job_name: gateway
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets: [host.docker.internal:8000]

  - job_name: retrieval
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets: [host.docker.internal:8001]

  - job_name: generation
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets: [host.docker.internal:8002]

  - job_name: otel-collector
    metrics_path: /metrics
    static_configs:
      - targets: [otel-collector:8888]
        labels:
          service: otel-collector-internal

  - job_name: otel-metrics
    metrics_path: /metrics
    static_configs:
      - targets: [otel-collector:8889]
        labels:
          service: otel-exported-metrics
